### ISSUE TITLE
How I can use usignal with uele instead of ulive?

### ISSUE THREAD

**Issue by eramax** [kethan/uele#1]
Thanks for such great library.

How I can use usignal with uele instead of ulive? I think it can be through the uele api, please provide an example.

this is my try [https://codesandbox.io/s/uele-app1-eskl3c?file=/src/index.jsx](https://codesandbox.io/s/uele-app1-eskl3c?file=/src/index.jsx)
Best,

**Comment by kethan** [comment]
Hi thanks for your interest on this library. As I am reallocating to a new place. I have don't have access to my laptop. For quick note i have given other options below for usignal.


https://github.com/kethan/uele#other-settings

Eg: https://codesandbox.io/s/uele-app1-forked-iznmpi?file=/src/index.jsx

**Comment by eramax** [comment]
Thanks so much
